steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t',
            'europe-west1-docker.pkg.dev/first-parser-427213-r4/javaapp:latest',
            '-f', 'gcp/gcp-devops/Dockerfile', # Specify the path to the Dockerfile
            'gcp/gcp-devops' # Specify the build context
          ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/europe-west1-docker.pkg.dev/first-parser-427213-r4/javaapp:latest']

logsBucket: 'gs://codebuildartifacts/'
options:
  logging: GCS_ONLY

# Store images in Google Artifact Registry 
images:
  - gcr.io/europe-west1-docker.pkg.dev/first-parser-427213-r4/javaapp:latest