steps:
- name: 'gcr.io/javaapp'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/javaapp:latest', '-t', 'gcr.io/$PROJECT_ID/javaapp:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/javaappyapp:$BUILD_ID', '.']
  id: 'build-image-javaapp'
  waitFor: ['-']
logsBucket: 'gs://codebuildartifacts'
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'gcr.io/$PROJECT_ID/javaapp:latest'
- 'gcr.io/$PROJECT_ID/javaapp:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/javaapp:$BUILD_ID'

