steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/first-parser-427213-r4/javaapp:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/first-parser-427213-r4/javaapp:latest']

images:
  - 'gcr.io/first-parser-427213-r4/javaapp:latest'
