steps:
- name: 'gcr.io/javaapp'
  args: ['build', '-t', 'gcr.io/first-parser-427213-r4/javaapp:latest', '-t', 'gcr.io/first-parser-427213-r4/javaapp:$COMMIT_SHA', '-t', 'gcr.io/first-parser-427213-r4/javaappyapp:$BUILD_ID', '.']
  id: 'build-image-javaapp'
  waitFor: ['-']
logsBucket: 'gs://codebuildartifacts/'
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'gcr.io/first-parser-427213-r4/javaapp:latest'
- 'gcr.io/first-parser-427213-r4/javaapp:$COMMIT_SHA'
- 'gcr.io/first-parser-427213-r4/javaapp:$BUILD_ID'

