steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t',
            'europe-west1-docker.pkg.dev/first-parser-427213-r4/javaapp:latest',
            '.'
          ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'europe-west1-docker.pkg.dev/first-parser-427213-r4/javaapp:latest']

# Store images in Google Artifact Registry 
images:
  - europe-west1-docker.pkg.dev/first-parser-427213-r4/javaapp:latest