steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build', 
            '-t',
            'gcr.io/first-parser-427213-r4/nodeapp:latest',
            '-f', 'gcp/gcp-devops-docker/Dockerfile', # Specify the path to the Dockerfile
            'gcp/gcp-devops-docker' # Specify the build context
          ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/first-parser-427213-r4/nodeapp:latest']

  # Configure kubectl with GKE creds
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
            'container', 'clusters', 'get-credentials',
            'upgrad',
            '--zone', 'us-central1-c'
          ]
  

  # # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
            'set', 'image',
            'deployment/nodeapp-deployment',
            'nodeapp-container=gcr.io/first-parser-427213-r4/nodeapp:latest'
          ]
          
logsBucket: 'gs://codebuildartifacts/'
options:
  logging: GCS_ONLY

# Store images in Google Artifact Registry 
images:
  - 'gcr.io/first-parser-427213-r4/nodeapp:latest'
